In [6]:
# import numpy as np
# import pandas as pd
# import matplotlib
# import matplotlib.pyplot as plt

In [7]:
# housing=pd.read_csv("data.csv")

In [8]:
#for plotting histograms
# housing.hist(bins=50 , figsize=(20,15))

## TRAIN-TEST SPLITTING

In [9]:
# def split_train_test(data,test_ratio):
#     np.random.seed(42)
#     shuffled=np.random.permutation(len(data))
#     test_set_size=int(len(data)*test_ratio)
#     test_indices=shuffled[:test_set_size]
#     train_indices=shuffled[test_set_size:]
#     return data.iloc[train_indices],data.iloc[test_indices]

# train_set,test_set=split_train_test(housing,0.2)
# print(len(train_set),len(test_set))

In [10]:
# the above code can also be implemented as :-
# from sklearn.model_selection import train_test_split
# train_set,test_set=train_test_split(housing,test_size=0.2,random_state=42)
# print(len(train_set),len(test_set))

# Stratified Smpling=>represnts whole population in test and train data 

In [11]:
# from sklearn.model_selection import StratifiedShuffleSplit
# split=StratifiedShuffleSplit(n_splits=1,test_size=0.2,random_state=42)

In [12]:
# for train_index,test_index in split.split(housing,housing['CHAS']):
#        strat_train_set=housing.loc[train_index]
#        strat_test_set=housing.loc[test_index]

In [13]:
# strat_train_set

In [14]:
# strat_train_set["CHAS"].value_counts()
# strat_test_set["CHAS"].value_counts()
# 94/7
# 376/28
#We can see that ratio of 0 and 1 are same in both training and testing data as per stratified shuffle

In [15]:
# housing=strat_train_set.copy()

## LOOKING FOR CORRELATIONS SO THAT WE CAN REMOVE OUTLIERS THAT AFFECT OUR MODEL


In [16]:
# corr_matrix=housing.corr()

In [17]:
# corr_matrix["MEDV"].sort_values(ascending=False)

In [18]:
# from pandas.plotting import scatter_matrix

In [19]:
# attributes=["MEDV","RM","ZN","LSTAT"]
# scatter_matrix(housing[attributes],figsize=(10,15))

In [20]:
# housing.plot(kind="scatter",x="RM",y="MEDV")

## ATTRIBUTE COMBINATIONS

In [21]:
#housing["TAXRM"]=housing["TAX"]/housing["RM"]

In [22]:
#housing["TAXRM"]

In [23]:
# housing.head()

In [24]:
#corr_matrix=housing.corr()

In [25]:
#corr_matrix["MEDV"].sort_values(ascending=False)

In [21]:
#housing.plot(kind="scatter",x="TAXRM",y="MEDV")

In [26]:
# housing=strat_train_set.drop("MEDV",axis=1)
# housing_labels=strat_train_set["MEDV"].copy()

## MISSING ATTRIBUTES

In [27]:
# To take care of missing attributes we have 3 options :-
#     GET RID OF MISSING DATA POINTS OF ALL ATTRIBUTES(depends on dataset size)
#     GET RID OF WHOLE ATTRIBUTE FROM DATASET(correlation dekh kar karna hga)
#     SET THE VALUE TO 0, MEAN OR MEDIAN(generally preferred)

In [28]:
#option 1(this is just a copy. orignal housing data remains unchnaged)
# a=housing.dropna(subset=["RM"])
# a.shape

In [29]:
# #option 2(we see no rm column is there and this is just a copy. orignal housing data remains unchnaged)
# a=housing.drop("RM",axis=1)
# a.shape

In [30]:
#option 3(we fit with median value and this is just a copy. orignal housing data remains unchnaged)
# median=housing["RM"].median()
# housing["RM"].fillna(median)
# housing.shape

In [31]:
# housing.describe()
#to see the decription before imputing

## median is very important as it has to be automatically applied to all the missing values in training and testing data as well as any upcoming data. we have sklearn library to do so

In [32]:
# from sklearn.impute import SimpleImputer 

In [33]:
# imputer=SimpleImputer(strategy="median")
# imputer.fit(housing)

In [34]:
# imputer.statistics_.shape
#it finds median of all the 15 cols so that kisi me bhi missing value ho to ye median usme fit ho jae

In [35]:
# X=imputer.transform(housing)

In [36]:
# housing_tr=pd.DataFrame(X,columns=housing.columns)

In [37]:
# housing_tr.describe()

## SKLEARN DESIGN

In [38]:
# Primarily 3 types  of object hai sklearn me:-
#     1.ESTIMATORS-estimates some parameters based on a dataset. eg: imputers.It has a fit() method that fits the dataset accordingly
#     and calculates the internal parameters.
    
#     2.TRANSFORMERS-Some estimator work as transformer.It takes input and return output based on learning from fit. It also has a 
#       convenience function ie fit_transform() which fits and then transforms.It is optimised to run together
    
#     3.PREDICTORS-Linear Regressors, KNN, are examples of predictor. They have fit() and predict(). It also gives score functions
#     that evaluates the score of goodness of predictions made.

##  Feature Scaling because generally all algo works well when all the feature values are on a same scale

In [35]:
# Two Types of feature scaling methods primarily:-
#     1. MIN-MAX SCALING(NORMALISATION)- (VALUE-MIN)/(MAX-MIN)(gives value between 0 to 1). We do this via MinMaxScaler
#     2. STANDARDISATION- (VALUE-MEAN)/(STANDARD DEVIATION)(variance=1). We do this via StandardScaler

## CREATING A PIPELINE-A CODE THAT CAN BE CHANGED EASILY AND THE MODEL CHANGES AUTOMATICALLY

In [39]:
# from sklearn.pipeline import Pipeline
# from sklearn.preprocessing import StandardScaler
# my_pipleline=Pipeline([
#     ('imputer',SimpleImputer(strategy="median")),
#     #... add as many as you want
#     ('std_scaler',StandardScaler())
# ])

In [40]:
# housing_num_tr=my_pipleline.fit_transform(housing)

In [41]:
# housing_num_tr.shape

## SELECTING THE MODEL

In [42]:
# from sklearn.linear_model import LinearRegression
# from sklearn.tree import DecisionTreeRegressor
# from sklearn.ensemble import RandomForestRegressor
# # model=LinearRegression()
# # model=DecisionTreeRegressor()
# model=RandomForestRegressor()
# model.fit(housing_num_tr,housing_labels)

In [43]:
# some_data=housing.iloc[:5]

In [44]:
# some_labels=housing_labels.iloc[:5]

In [45]:
# prepared_data=my_pipleline.transform(some_data)

In [46]:
# model.predict(prepared_data)

In [47]:
# list(some_labels)

## evaluating the model

In [48]:
# from sklearn.metrics import  mean_squared_error
# housing_predictions=model.predict(housing_num_tr)
# mse=mean_squared_error(housing_labels,housing_predictions)
# rmse=np.sqrt(mse)
# rmse



# this linear regression model gives a lot of error so we discard this model and use decision tree regressor but decision tree
#gives overfitting

## Cross Validation

In [46]:
from sklearn.model_selection import cross_val_score
scores=cross_val_score(model,housing_num_tr,housing_labels,scoring="neg_mean_squared_error",cv=10)
rmse=np.sqrt(-scores)

In [47]:
rmse

array([3.80902454, 2.56400132, 5.13971187, 3.10062673, 3.08174961,
       2.0031091 , 3.30268443, 3.48339344, 2.12404257, 3.94501676])

In [48]:
def print_scores(scores):
    print(f"Scores: {scores}")
    print(f"Mean: {scores.mean()}")
    print(f"STD: {scores.std()}")

In [49]:
print_scores(rmse)

Scores: [3.80902454 2.56400132 5.13971187 3.10062673 3.08174961 2.0031091
 3.30268443 3.48339344 2.12404257 3.94501676]
Mean: 3.2553360366745436
STD: 0.8813207650390685


## Saving the model

In [50]:
from joblib import dump,load

In [51]:
dump(model,"Dracula.joblib")

['Dracula.joblib']

## Testing the model

In [59]:
# X_test=strat_test_set.drop("MEDV",axis=1)
# Y_test=strat_test_set["MEDV"].copy()
# X_test_prepared=my_pipleline.transform(X_test)
# final_predictions=model.predict(X_test_prepared)
# final_mse=mean_squared_error(Y_test,final_predictions)
# final_rmse=np.sqrt(final_mse)
# print(final_predictions,list(Y_test))

[23.129 22.195 47.085 32.101 45.409 34.182 20.757 24.041 32.989 19.978
 19.374 29.298 22.072 32.199 20.389 19.097 12.81  20.802 27.647 19.658
 19.903 45.827 12.082 14.497 25.748 33.225 16.031 15.258  7.042 19.934
 23.732 23.287 17.526 14.726 21.121 18.694 22.148 17.34  45.886 17.575
 21.179 19.085 19.548 18.508 32.855  8.47  25.075 14.46  20.52  21.583
 47.037 24.59  15.103 21.82  19.767 46.578 32.917 20.293 34.14  10.447
 23.695 36.15  32.88  23.856 13.941 21.224 20.405 15.814 28.038 24.569
 23.843 32.11  19.361 31.186 10.675 20.444 41.993 19.573 19.9   15.289
 42.119  9.332 22.897 22.622 27.714 16.317 23.027 22.566 20.388 18.78
 26.518 11.015 33.664 12.856 25.675 20.085 33.061 14.031 20.66  21.197
 20.166] [24.6, 22.0, 44.8, 23.6, 48.8, 36.5, 19.7, 23.1, 34.6, 21.5, 23.1, 15.0, 23.0, 34.9, 18.5, 10.4, 10.2, 18.9, 23.9, 19.3, 19.4, 48.3, 10.9, 13.6, 27.5, 37.3, 16.1, 15.2, 10.5, 21.4, 23.2, 20.7, 21.7, 13.0, 22.3, 19.6, 21.2, 18.1, 50.0, 23.7, 22.6, 20.5, 18.9, 19.5, 32.7, 8.8, 29.1, 

In [55]:
# final_rmse

3.2219481023532053

In [61]:
# prepared_data[0]

array([-0.44214569,  3.18549186, -1.12157806, -0.27288841, -1.42038605,
       -0.5507194 , -1.74081446,  2.56373713, -0.9938038 , -0.57365513,
       -0.98653542,  0.43847588, -0.49179946])

## USING THE MODEL

In [62]:
# from joblib import dump,load
# import numpy as np
# model=load("Dracula.joblib")
# features=np.array([-0.44214569,  3.18549186, -1.12157806, -0.27288841, -1.42038605,
#        -0.5507194 , -1.74081446,  2.56373713, -0.9938038 , -0.57365513,
#        -0.98653542,  0.43847588, -0.49179946])
# model.predict([features])

array([20.557])